# Project paths are relative to this repository root.
paths:

  #  Annotations paths
  persons_annotations: persons_annotations

  #  outputs paths
  checkpoints: checkpoints
  predictions: predictions
  plots: plots
  logs: logs

dataset:
  max_players: 12
  image_size: [224, 224]

model:
  num_classes: 9
  classes: ['standing','setting','waiting','moving','falling','spiking','jumping','digging','blocking',]


training:
  batch_size: 8
  epochs: 25
  learning_rate: 0.0001
  weight_decay: 0.0001
  optimizer: AdamW
  device: auto
  num_workers: 2
  early_stopping: True
  save_interval: 5

experiment:
  log: 5